/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import styles from './SidebarCollapse.module.css'

const menuItems = [
  {
    icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/886101deab7e20e359e761740ebf52dcfd1db223a9856394124b42cfa79b02a1?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa',
    label: 'Dashboard',
  },
  {
    icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/23ee01b62a9efeb112d21166481d43f543bd0397970d8491aa8838216664d87e?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa',
    label: 'Analytics',
  },
  {
    icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/fbdf920b70f9fb9c3910db6bac5be39ad4d7fd71ddfe67552801bba1ac2c440e?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa',
    label: 'Reports',
  },
  {
    icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/5f9b46c0ff4fba6636c5b995018f2a174cacbf0ac12286af82187fe8dcf8b876?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa',
    label: 'Settings',
  },
]

const MenuItem = ({ icon, label }) => (
  <div className={styles.menuItem}>
    <img loading="lazy" src={icon} alt="" className={styles.menuItemIcon} />
    <span className={styles['visually-hidden']}>{label}</span>
  </div>
)

function SidebarCollapse() {
  return (
    <nav className={styles.sidebar}>
      <div className={styles.tooltipContainer}>
        <div className={styles.tooltipArrow}>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/6b04973d94d94081f73a264076f56b81cb3fdc294985780e5bddbf8b3267ad98?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa"
            alt=""
            className={styles.tooltipArrowImage}
          />
        </div>
        <div className={styles.tooltipContent}>Tổng quan</div>
      </div>
      <header className={styles.logo}>CS</header>
      <div className={styles.menuContainer}>
        <div className={styles.mainMenu}>
          {menuItems.map((item, index) => (
            <MenuItem key={index} icon={item.icon} label={item.label} />
          ))}
        </div>
      </div>
    </nav>
  )
}

export default SidebarCollapse
