/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import styles from './ProfileCard.module.css'

const Divider = () => {
  return <hr className={styles.divider} />
}

export default Divider
