/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import styles from './ProfileCard.module.css'

const MenuItem = ({ icon, label }) => {
  return (
    <button className={styles.menuItem}>
      <img loading="lazy" src={icon} alt="" className={styles.menuIcon} />
      <span className={styles.menuLabel}>{label}</span>
    </button>
  )
}

export default MenuItem
