/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import styles from './ProfileCard.module.css'

const ProfileImage = ({ src, alt }) => {
  return (
    <img loading="lazy" src={src} alt={alt} className={styles.profileImage} />
  )
}

export default ProfileImage
