/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import styles from './ProfileCard.module.css'

const UserInfo = ({ name, phone }) => {
  return (
    <div className={styles.userInfo}>
      <h2 className={styles.userName}>{name}</h2>
      <p className={styles.userPhone}>{phone}</p>
    </div>
  )
}

export default UserInfo
