/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import styles from './MetricsOverview.module.css'

export function MetricsOverview() {
  return (
    <section className={styles.metricsOverview}>
      <h2 className={styles.title}>Tổng quan về số liệu</h2>
      <p className={styles.subtitle}>
        Thống kế tổng quan về SMS, email và nhiệm vụ
      </p>
      <div className={styles.metrics}>
        <div className={styles.metric}>
          <h3 className={styles.metricTitle}>SMS đã gửi</h3>
          <div className={styles.metricContent}>
            <div className={styles.metricMain}>
              <img
                src="/icons/sms.png"
                alt="SMS"
                className={styles.metricIcon}
              />
              <span className={styles.metricValue}>23.680</span>
            </div>
            <div className={styles.metricDetails}>
              <p className={styles.metricDetail}>21.100 SMS thành công</p>
              <p className={styles.metricDetail}>1.680 SMS thất bại</p>
            </div>
          </div>
        </div>

        <div className={styles.divider} />

        <div className={styles.metric}>
          <h3 className={styles.metricTitle}>Email</h3>
          <div className={styles.metricContent}>
            <div className={styles.metricMain}>
              <img
                src="/icons/email.png"
                alt="Email"
                className={styles.metricIcon}
              />
              <span className={styles.metricValue}>529</span>
            </div>
            <p className={styles.metricDetail}>Đã gửi thành công</p>
          </div>
        </div>

        <div className={styles.divider} />

        <div className={styles.metric}>
          <h3 className={styles.metricTitle}>Nhiệm vụ</h3>
          <div className={styles.metricContent}>
            <div className={styles.metricMain}>
              <img
                src="/icons/task.png"
                alt="Tasks"
                className={styles.metricIcon}
              />
              <span className={styles.metricValue}>189</span>
            </div>
            <p className={styles.metricDetail}>123 nhiệm vụ hoàn thành</p>
          </div>
        </div>
      </div>
    </section>
  )
}
