/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import { Line } from 'react-chartjs-2'
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js'

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
)

export function LineChart({ className }) {
  const options = {
    responsive: true,
    plugins: {
      legend: {
        display: false,
      },
    },
    scales: {
      x: {
        grid: {
          display: false,
        },
      },
      y: {
        grid: {
          color: '#F4F5F9',
        },
      },
    },
    maintainAspectRatio: false,
  }

  const labels = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul']

  const data = {
    labels,
    datasets: [
      {
        label: 'Khách hàng',
        data: labels.map(() => Math.floor(Math.random() * 1000)),
        borderColor: '#165BAA',
        backgroundColor: '#165BAA',
        tension: 0.4,
      },
    ],
  }

  return (
    <div className={className}>
      <Line options={options} data={data} />
    </div>
  )
}
