/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import styles from './AttachedFiles.module.css'

const images = [
  'https://cdn.builder.io/api/v1/image/assets/TEMP/23db701b0404dcd471df66d110d55a127d0e62bc228b67653dbf86b40ae4913c?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa',
  'https://cdn.builder.io/api/v1/image/assets/TEMP/f9b27a81e86749fbb7a86f8a09ec69e657c011aa80a4b3bba1da1293814a6e55?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa',
  'https://cdn.builder.io/api/v1/image/assets/TEMP/f66edb685d49222636dbff9afcc414d978e6139d28a4f7bd856c53c2783eb315?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa',
  'https://cdn.builder.io/api/v1/image/assets/TEMP/3cf927de4c256770a9eee3c34459a55ee2bac5f6b0f73db1eb8e8f65adfc158c?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa',
  'https://cdn.builder.io/api/v1/image/assets/TEMP/e4c809aaadd3a5357f62ae48089c588023a5c3271f400212195f89f7259aa361?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa',
  'https://cdn.builder.io/api/v1/image/assets/TEMP/5133182dd6b66fa03c17daffaa8571870bf4d28a424bee4406e0c30a10ffd168?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa',
  'https://cdn.builder.io/api/v1/image/assets/TEMP/e87069478ae2fb55e274e569b8b665b6677ebea35711872933959daf573f0d2e?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa',
  'https://cdn.builder.io/api/v1/image/assets/TEMP/34d0ba11eda019c9982556d7c28fb7bd799f4dfa82c0ebcaacc365ed3e2153f4?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa',
]

function AttachedFiles() {
  return (
    <section className={styles.attachedFiles}>
      <header className={styles.filesHeader}>
        <h3 className={styles.filesTitle}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/826de0fd491dc0e3ef1dc6a23a0f8af2dce68ed188b769dc28801ac3b62e71d2?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa"
            alt=""
            className={styles.filesIcon}
          />
          Ảnh và tập tin đính kèm
        </h3>
        <button className={styles.expandButton}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/5cdd11a77e523781aac44ca80d78d548fcac0e31cb895f6c2818a848fa427fca?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa"
            alt="Expand"
            className={styles.expandIcon}
          />
        </button>
      </header>
      <nav className={styles.filesNav}>
        <button className={`${styles.navButton} ${styles.active}`}>
          Hình ảnh
        </button>
        <button className={styles.navButton}>Tập tin</button>
      </nav>
      <div className={styles.imageGrid}>
        {images.map((src, index) => (
          <img
            key={index}
            src={src}
            alt={`Attached file ${index + 1}`}
            className={styles.attachedImage}
          />
        ))}
      </div>
      <button className={styles.viewMoreButton}>Xem thêm</button>
    </section>
  )
}

export default AttachedFiles
