/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import styles from './ChatMain.module.css'
import ChatHeader from './ChatHeader'
import ChatThread from './ChatThread'
import ChatInput from './ChatInput'

function ChatMain() {
  return (
    <main className={styles.messageThread}>
      <ChatHeader />
      <ChatThread />
      <ChatInput />
    </main>
  )
}

export default ChatMain
