/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import styles from './ChatMessage.module.css'

function ChatMessage({ sender, content, avatar, image }) {
  const isAgent = sender === 'agent'
  const messageClass = isAgent ? styles.agentMessage : styles.userMessage

  return (
    <div className={`${styles.messageContainer} ${messageClass}`}>
      {!isAgent && avatar && (
        <img src={avatar} alt="User avatar" className={styles.avatar} />
      )}
      {image ? (
        <img
          src={image}
          alt="Attached image"
          className={styles.attachedImage}
        />
      ) : (
        <p className={styles.messageContent}>{content}</p>
      )}
    </div>
  )
}

export default ChatMessage
