/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import styles from './ChatInput.module.css'

function ChatInput() {
  return (
    <form className={styles.messageEditor}>
      <div className={styles.inputContainer}>
        <input
          type="text"
          placeholder="Nhập tin nhắn"
          className={styles.inputField}
          aria-label="Enter message"
        />
        <button type="button" className={styles.attachButton}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/759d02b0ef865715624d19a407172d264e07f5e33374406d3360f7a5ce910961?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa"
            alt="Attach file"
          />
        </button>
        <button type="button" className={styles.emojiButton}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/e7d85521c093a3c11bfc87f46e588aae1fc188abd11ccc449fd12c892ef5f0d3?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa"
            alt="Insert emoji"
          />
        </button>
      </div>
      <div className={styles.actionBar}>
        <span className={styles.brand}>PNJ</span>
        <div className={styles.actionButtons}>
          <button type="button" className={styles.actionButton}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/86c7d949ef9234e3bd219b232100a613e1aa6784da7bd0e0c83e444e9eda0200?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa"
              alt="Action 1"
            />
          </button>
          <button type="button" className={styles.actionButton}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/a8a835a604f5330b2988072267943bd9fc741ad16f538574f05c3b63302098c3?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa"
              alt="Action 2"
            />
          </button>
          <button type="button" className={styles.actionButton}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/a3a96ce1d65f885c0a1fc980732cae749cb24b3afd93c8498b063f2765d3658d?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa"
              alt="Action 3"
            />
          </button>
          <button type="button" className={styles.actionButton}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/4cdc42b0ca2ad78f70e4d6832432af7c25868d335d61b02f1110cea7a54b25fe?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa"
              alt="Action 4"
            />
          </button>
          <button type="button" className={styles.actionButton}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/f306df6c31f3cd44350edbdd894eba6a4afc022ab8dbc22997ede3baab58b796?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa"
              alt="Action 5"
            />
          </button>
          <button type="button" className={styles.actionButton}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/953cf47d46169c987bf933668c9992f9120331c547a79c6d78623536f413ce8f?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa"
              alt="Action 6"
            />
          </button>
        </div>
      </div>
    </form>
  )
}

export default ChatInput
