/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import styles from './ChatNotes.module.css'

const notes = [
  {
    id: 1,
    author: 'Sam Sam',
    time: '15:22',
    content: 'Địa chỉ thứ 2: Xã Cao Sơn, Huyện Bạch Thông, Bắc Kạn',
  },
  {
    id: 2,
    author: 'Jasmin',
    time: '26/09',
    content: 'Khách cần chăm sóc kỹ!!!',
  },
]

function ChatNotes() {
  return (
    <section className={styles.chatNotes}>
      <header className={styles.notesHeader}>
        <h3 className={styles.notesTitle}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/2f484a34558a6a2d06ce76db94c70cf645271f57debb2e170ebbf2e0a50df95b?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa"
            alt=""
            className={styles.notesIcon}
          />
          Ghi chú (2)
        </h3>
        <button className={styles.addNoteButton}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/9d3a49b4eb005064b0c26b8f024eed539c640d94cfaf382ec26d26e877788e95?placeholderIfAbsent=true&apiKey=96d3f0d387684778814e4c6d174285fa"
            alt="Add note"
            className={styles.addIcon}
          />
        </button>
      </header>
      <div className={styles.notesList}>
        {notes.map(note => (
          <div key={note.id} className={styles.noteItem}>
            <div className={styles.noteHeader}>
              <span className={styles.noteAuthor}>
                <img
                  src={`http://b.io/ext_8${note.id}-`}
                  alt=""
                  className={styles.authorIcon}
                />
                {note.author}
              </span>
              <span className={styles.noteTime}>{note.time}</span>
            </div>
            <p className={styles.noteContent}>{note.content}</p>
          </div>
        ))}
      </div>
      <textarea
        className={styles.newNoteInput}
        placeholder="Nhập ghi chú (Enter để gửi)"
        aria-label="Enter a new note"
      />
    </section>
  )
}

export default ChatNotes
